### ISSUE TITLE
All logs are going to `stderr`

### ISSUE THREAD

**Issue by MartinquaXD** [cowprotocol/dune-sync#36]
`dune-sync` pods are currently flooding `#alerts-prod` because all logs are going to `stderr`.
This can be seen in our logs [here](https://production-6de61f.kb.eu-central-1.aws.cloud.es.io/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-7d%2Fd,to:now))&_a=(columns:!(log),filters:!(),grid:(columns:('@timestamp':(width:164))),index:c0e240e0-d9b3-11ed-b0e6-e361adffce0b,interval:auto,query:(language:kuery,query:'kubernetes.pod_name:%20%22order-rewards-cronjob%22%20and%20stream:%20stderr'),sort:!(!('@timestamp',desc)))).
This is true for `batch-rewards`, `app-data`, `app-data` and probably all `dune-sync` pods.

**Comment by bh2smith** [comment]
I don't think the is an issue with this repo. Sounds like a devops thing. Everything has been running just fine for months now and they just performed some sort of migration. So I will differ this issue to @ahhda and spawn a new one in https://github.com/cowprotocol/infrastructure/

**Comment by nlordell** [comment]
Re-opening this as it appears that indeed, all logs are going to `stderr` when running with the project's docker image:

```
docker run \
  -v $(pwd)/data:/app/data \
  --env-file .env \
  ghcr.io/cowprotocol/dune-sync:main \
  --sync-table batch_rewards --dry-run true \
  1> out.txt 2> err.txt
```

Note that we redirect output in ☝️ to `out.txt` for stdout and `err.txt` for stderr.

`out.txt` is empty:
```
% cat out.txt

```

`err.txt` contains `INFO` logs, so non-error logs are going to `stderr` which would cause alert noise:
```
% cat err.txt
2023-05-01 09:52:40,692 INFO root Global Log Level configured as INFO
2023-05-01 09:52:43,574 INFO botocore.credentials Found credentials in environment variables.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/src/main.py", line 80, in <module>
    sync_batch_rewards(
  File "/app/src/sync/order_rewards.py", line 87, in sync_batch_rewards
    block_from=last_sync_block(
  File "/app/src/sync/common.py", line 13, in last_sync_block
    block_from = aws.last_sync_block(table)
  File "/app/src/post/aws.py", line 230, in last_sync_block
    table_files = self.existing_files().get(table_str)
  File "/app/src/post/aws.py", line 217, in existing_files
    service_resource = self._assume_role()
  File "/app/src/post/aws.py", line 134, in _assume_role
    internal_assumed_role_object = sts_client.assume_role(
  File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.10/site-packages/botocore/client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidClientTokenId) when calling the AssumeRole operation: The security token included in the request is invalid.
```

Note that the error is expected, as I did not correctly configure AWS credentials.
